import { ReactElement } from 'react'
import Head from 'next/head'
import styles from '@/layout/Layout.module.scss'

type LayoutProps = Required<{
  readonly children: ReactElement
}>

export const Layout = ({ children }: LayoutProps) => (
  <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    
    <div className={styles.lContainer}>
      { children }
    </div>
  </>
)